name: Cypress Manual Run

on:
  workflow_dispatch:
    inputs:
      spec:
        description: 'Spec file to run'
        required: false
        default: ''

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18.18.2

      - run: npm ci
      - run: npx cypress install

      - name: Run Cypress
        run: |
          if [ -z "${{ github.event.inputs.spec }}" ]; then
            npx cypress run
          else
            npx cypress run --spec ${{ github.event.inputs.spec }}
          fi
